services:
  server:
    image: outline-app-python-3.10:latest
    container_name: outline-api-server
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - SETTINGS_MODULE=settings.prod
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./logs:/app/logs
      - ./media:/app/media
    ports:
      - "127.0.0.1:8000:8000"
    command: python -m server --host 0.0.0.0 --port 8000 run

  bot:
    image: outline-app-python-3.10:latest
    container_name: outline-bot
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - SETTINGS_MODULE=settings.prod
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python -m bot run

  assets:
    image: node:22.14
    container_name: outline-assets
    volumes:
      - ./app_server/assets:/app_server/assets
      - ./static:/static
    working_dir: /app_server/assets/
    command: bash -c "yarn install && yarn schema:generate && yarn run build-only"

  assets-installation:
    image: node:22.14
    container_name: outline-assets-installation
    volumes:
      - ./app_server/assets:/app_server/assets
      - ./static:/static
    working_dir: /app_server/assets/
    command: bash -c "yarn install && yarn schema:generate && yarn run build-only:installation"
